### ISSUE TITLE
Hartnett lettering 

### ISSUE THREAD

**Issue by YXH1992** [HartnettGallery/wordpress#16]
This is how it should look, continuoys white from top of footing to bottom. No gray line going on top of white letters. The design should look exaclty the way the original pictures were submitted, unless its impossible to do.

you can see a black/gray line on top and bottomo of letters

[9:30] 
if necessary, the letters should overflow the bakcground and bottomo frame by a couple of pixels

![pasted_image_at_2017_04_29_09_29_pm_720](https://cloud.githubusercontent.com/assets/27938112/25560507/bc8637d8-2d23-11e7-9ff8-5a79fbfef703.png)
![hartnett_lettering_720](https://cloud.githubusercontent.com/assets/27938112/25560508/be23af26-2d23-11e7-97b3-75ae4d47f71a.jpg)

**Comment by MohanL** [comment]
![image](https://cloud.githubusercontent.com/assets/10900547/25565029/d6fa3a78-2d8d-11e7-981e-9d5ccabd33e3.png)
