### ISSUE TITLE
Hartnett floorplan carousel preview ratio 

### ISSUE THREAD

**Issue by YXH1992** [HartnettGallery/wordpress#18]
<img width="1280" alt="screen shot 2017-05-09 at 8 46 35 pm" src="https://cloud.githubusercontent.com/assets/27938112/25878458/cd199ad6-34f8-11e7-9e23-2837fdfbe0b1.png">
 
The ratio of the Hartnett floorplan is distorted in the carousel preview. It would be great if the viewer can see the original image. 

Thankss!

**Comment by MohanL** [comment]
fixed
