### ISSUE TITLE
Standardize margins 

### ISSUE THREAD

**Issue by YXH1992** [HartnettGallery/wordpress#5]
“proposal_submit” and “exhibition_current” have different margins

**Comment by YXH1992** [comment]
以主页的边距为模板，调整proposal—floorplan, pictures和exhibition-current, previous页面的边距。见下图
<img width="1280" alt="screen shot 2017-04-30 at 12 16 34 pm" src="https://cloud.githubusercontent.com/assets/27938112/25565977/661fa7a4-2d9f-11e7-9bf6-0c494675aa12.png">
<img width="1280" alt="screen shot 2017-04-30 at 12 20 40 pm" src="https://cloud.githubusercontent.com/assets/27938112/25565983/84ec02c2-2d9f-11e7-93f5-8b55abf1c45b.png">
<img width="1280" alt="screen shot 2017-04-30 at 12 21 02 pm" src="https://cloud.githubusercontent.com/assets/27938112/25565984/87e3da9a-2d9f-11e7-8172-79387bd0e927.png">
<img width="1280" alt="screen shot 2017-04-30 at 12 21 10 pm" src="https://cloud.githubusercontent.com/assets/27938112/25565986/8a25352e-2d9f-11e7-8160-d7792de9b2d7.png">

**Comment by MohanL** [comment]
done
